#!/bin/bash

files='ca_wac_2015.sql ca_rac_2015.sql ca_od_2015.sql ca_xwalk.sql il_wac_2015.sql il_rac_2015.sql il_od_2015.sql il_xwalk.sql'

for file in $files
do
  unzip ~/data/${file}.zip -d ~/data/
  sqlite3 lodes.db < ~/data/${file}
  rm ~/data/${file}
done

csvfiles = 'ca_wac_S000_JT00_2015'

for file in $csvfiles
do
  unzip ~/data/${file}.zip -d ~/data/content/03-intro-python/
done